binop_separator = "Back"
comment_width = 120
imports_granularity = "Crate"
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true

# Ignore automatically-generated code.
ignore = ["abi/src/bindings"]
